### ISSUE TITLE
Use with js

### ISSUE THREAD

**Issue by fair-man** [mongoose-os-libs/rpc-ws#2]
Hello. Tell me, please, how to use this library with js? Can I have a sample code, or a link to the documentation?

**Comment by cpq** [comment]
https://mongoose-os.com/docs/mongoose-os/userguide/rpc.md

**Comment by fair-man** [comment]
A very complex example. If I understand correctly, you need to make some kind of binding over C ++. Someone can do this so that you can just do load ('api_ws.js'), and then call some open method? For example, how is this implemented for api_dht.js
![Screenshot_1](https://user-images.githubusercontent.com/11162127/71425353-c1732280-26ac-11ea-8399-dea9a9d9b722.png)
