### ISSUE TITLE
Javascripts wrapper implementation request

### ISSUE THREAD

**Issue by fair-man** [mongoose-os-libs/rpc-ws#3]
https://mongoose-os.com/docs/mongoose-os/userguide/rpc.md

A very complex example. If I understand correctly, you need to make some kind of binding over C ++. Someone can do this so that you can just do load ('api_ws.js'), and then call some open method? For example, how is this implemented for api_dht.js

![Screenshot_1](https://user-images.githubusercontent.com/11162127/71436977-af22d400-2700-11ea-91ce-b5ba6eebbecb.png)

**Comment by fair-man** [comment]
Any updates?

**Comment by cpq** [comment]
This library does not need an RPC wrapper. It just enables Websocket transport for the JSON-RPC. The API you need to use is RPC's API, and JS wrapper already exists for it:

https://mongoose-os.com/docs/mongoose-os/api/rpc/rpc-common.md#rpcaddhandler
